# ──────────────────────────────────────────────────────────────────────────────
# Stage 1 — deps
# Install ALL node_modules (including devDeps needed by the build stage).
# Isolated so this expensive layer is only rebuilt when lockfile changes.
# ──────────────────────────────────────────────────────────────────────────────
FROM node:20-alpine AS deps

# libc6-compat is required by some native addons on Alpine (e.g. sharp)
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy manifests first for optimal layer caching
COPY package.json package-lock.json ./

RUN npm ci --frozen-lockfile

# ──────────────────────────────────────────────────────────────────────────────
# Stage 2 — builder
# Compile the Next.js 16 production bundle (standalone output).
# NEXT_PUBLIC_* vars are baked into the client bundle at build time — they
# must be passed as build ARGs so the resulting image stays portable.
# ──────────────────────────────────────────────────────────────────────────────
FROM node:20-alpine AS builder

WORKDIR /app

# Carry over installed node_modules from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy full source (see .dockerignore for what is excluded)
COPY . .

# Build-time public env var — passed via docker-compose `args:`
ARG NEXT_PUBLIC_QUICKNODE_RPC_URL
ENV NEXT_PUBLIC_QUICKNODE_RPC_URL=${NEXT_PUBLIC_QUICKNODE_RPC_URL}

# Suppress Next.js build telemetry
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

# ──────────────────────────────────────────────────────────────────────────────
# Stage 3 — runner (final production image)
# Uses .next/standalone output — only the minimal server.js bundle is kept.
# No node_modules or source code exist in this image.
# ──────────────────────────────────────────────────────────────────────────────
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Run as non-root for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid 1001 nextjs

# Standalone server bundle (generated by output: 'standalone' in next.config.ts)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# Static assets must be copied separately into the standalone dir
COPY --from=builder --chown=nextjs:nodejs /app/public       ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

# Port the standalone server listens on (read by server.js)
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

EXPOSE 3000

# Healthcheck using Node.js built-in (no wget/curl needed in minimal alpine image)
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \
  CMD node -e "require('http').get('http://localhost:3000/', (r) => { process.exit(r.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"

CMD ["node", "server.js"]
